import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import matches.models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("short_name", models.CharField(blank=True, max_length=12)),
                ("primary_color", models.CharField(default="#19C37D", max_length=7)),
                ("secondary_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("competition", models.CharField(blank=True, max_length=160)),
                ("venue", models.CharField(blank=True, max_length=160)),
                ("kickoff_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Brouillon"), ("uploaded", "Vidéo importée"), ("queued", "En attente"), ("processing", "Analyse en cours"), ("review", "À valider"), ("completed", "Terminé"), ("failed", "Échec")], default="draft", max_length=24)),
                ("home_score", models.PositiveSmallIntegerField(default=0)),
                ("away_score", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("away_team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="away_matches", to="matches.team")),
                ("home_team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="home_matches", to="matches.team")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("shirt_number", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ("position", models.CharField(choices=[("GK", "Gardien"), ("CB", "Défenseur central"), ("FB", "Latéral"), ("DM", "Milieu défensif"), ("CM", "Milieu central"), ("AM", "Milieu offensif"), ("W", "Ailier"), ("ST", "Attaquant"), ("OTHER", "Autre")], default="OTHER", max_length=12)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="players", to="matches.team")),
            ],
            options={"ordering": ["team__name", "shirt_number", "name"]},
        ),
        migrations.CreateModel(
            name="MatchVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=matches.models.match_video_upload_to)),
                ("original_name", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("duration_ms", models.PositiveBigIntegerField(default=0)),
                ("fps", models.FloatField(default=0)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("codec", models.CharField(blank=True, max_length=64)),
                ("quality_grade", models.CharField(choices=[("unknown", "Non évaluée"), ("A", "A — Analyse complète"), ("B", "B — Bonne"), ("C", "C — Limitée"), ("reject", "Insuffisante")], default="unknown", max_length=16)),
                ("quality_score", models.FloatField(default=0)),
                ("quality_metrics", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("match", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="video", to="matches.match")),
            ],
        ),
        migrations.CreateModel(
            name="MatchPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=32)),
                ("video_start_ms", models.PositiveBigIntegerField()),
                ("video_end_ms", models.PositiveBigIntegerField()),
                ("match_clock_start_ms", models.PositiveBigIntegerField(default=0)),
                ("match_clock_end_ms", models.PositiveBigIntegerField(default=2700000)),
                ("source", models.CharField(choices=[("auto", "Automatique"), ("manual", "Manuel")], default="auto", max_length=12)),
                ("confidence", models.FloatField(default=0)),
                ("confirmed", models.BooleanField(default=False)),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="periods", to="matches.match")),
            ],
            options={
                "ordering": ["number"],
                "constraints": [models.UniqueConstraint(fields=("match", "number"), name="unique_match_period")],
            },
        ),
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("queued", "En attente"), ("processing", "En cours"), ("review", "À valider"), ("completed", "Terminé"), ("failed", "Échec"), ("cancelled", "Annulé")], default="queued", max_length=24)),
                ("current_stage", models.CharField(choices=[("queued", "Mise en file"), ("probe", "Lecture vidéo"), ("quality", "Contrôle qualité"), ("periods", "Détection des périodes"), ("tracking", "Tracking joueurs et ballon"), ("camera", "Calibration caméra"), ("possession", "Ball in play et possession"), ("events", "Détection des actions"), ("stats", "Calcul des statistiques"), ("clips", "Découpage vidéo"), ("report", "Rapport final"), ("done", "Terminé")], default="queued", max_length=24)),
                ("progress", models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ("config", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analysis_runs", to="matches.match")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AnalysisArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("quality", "Qualité vidéo"), ("periods", "Périodes"), ("tracking", "Tracking"), ("camera", "Caméra"), ("events", "Événements"), ("report", "Rapport"), ("annotated_video", "Vidéo annotée")], max_length=32)),
                ("file", models.FileField(upload_to=matches.models.artifact_upload_to)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="matches.analysisrun")),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("track_uid", models.CharField(max_length=80)),
                ("role", models.CharField(choices=[("player", "Joueur"), ("goalkeeper", "Gardien"), ("referee", "Arbitre"), ("other", "Autre")], default="player", max_length=20)),
                ("predicted_shirt_number", models.SmallIntegerField(blank=True, null=True)),
                ("identity_confidence", models.FloatField(default=0)),
                ("video_start_ms", models.PositiveBigIntegerField(default=0)),
                ("video_end_ms", models.PositiveBigIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("analysis_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tracks", to="matches.analysisrun")),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tracks", to="matches.match")),
                ("player", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="matches.player")),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="matches.team")),
            ],
            options={
                "ordering": ["video_start_ms"],
                "constraints": [models.UniqueConstraint(fields=("analysis_run", "track_uid"), name="unique_analysis_track")],
            },
        ),
        migrations.CreateModel(
            name="PossessionSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(choices=[("controlled", "Contrôlé"), ("contested", "Disputé"), ("loose", "Ballon libre"), ("out", "Ballon sorti"), ("unknown", "Inconnu")], max_length=16)),
                ("video_start_ms", models.PositiveBigIntegerField()),
                ("video_end_ms", models.PositiveBigIntegerField()),
                ("match_start_ms", models.PositiveBigIntegerField()),
                ("match_end_ms", models.PositiveBigIntegerField()),
                ("confidence", models.FloatField(default=0)),
                ("reviewed", models.BooleanField(default=False)),
                ("analysis_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="possessions", to="matches.analysisrun")),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="possessions", to="matches.match")),
                ("owner_track", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="possession_segments", to="matches.track")),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="possessions", to="matches.matchperiod")),
                ("player", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="matches.player")),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="matches.team")),
            ],
            options={"ordering": ["video_start_ms"]},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("pass", "Passe"), ("carry", "Conduite"), ("dribble", "Dribble"), ("header", "Tête"), ("high_pass", "Passe haute"), ("cross", "Centre"), ("throw_in", "Touche"), ("shot", "Tir"), ("goal", "But"), ("tackle", "Tacle"), ("block", "Blocage"), ("interception", "Interception"), ("duel", "Duel"), ("aerial_duel", "Duel aérien"), ("recovery", "Récupération"), ("loss", "Perte"), ("foul", "Faute"), ("offside", "Hors-jeu"), ("free_kick", "Coup franc"), ("corner", "Corner"), ("penalty", "Penalty"), ("save", "Arrêt"), ("out", "Sortie du ballon"), ("other", "Autre")], max_length=32)),
                ("subtype", models.CharField(blank=True, max_length=64)),
                ("video_time_ms", models.PositiveBigIntegerField()),
                ("match_time_ms", models.PositiveBigIntegerField()),
                ("start_x", models.FloatField(blank=True, null=True)),
                ("start_y", models.FloatField(blank=True, null=True)),
                ("end_x", models.FloatField(blank=True, null=True)),
                ("end_y", models.FloatField(blank=True, null=True)),
                ("outcome", models.CharField(choices=[("success", "Réussi"), ("failure", "Raté"), ("neutral", "Neutre"), ("unknown", "Inconnu")], default="unknown", max_length=16)),
                ("confidence", models.FloatField(default=0)),
                ("visibility", models.CharField(default="unknown", max_length=24)),
                ("qualifiers", models.JSONField(blank=True, default=list)),
                ("review_status", models.CharField(choices=[("auto_accepted", "Accepté automatiquement"), ("pending", "À valider"), ("validated", "Validé"), ("corrected", "Corrigé"), ("rejected", "Rejeté")], default="pending", max_length=24)),
                ("source", models.CharField(default="ai", max_length=32)),
                ("model_version", models.CharField(default="baseline-v1", max_length=64)),
                ("clip", models.FileField(blank=True, upload_to=matches.models.event_clip_upload_to)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_track", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actor_events", to="matches.track")),
                ("analysis_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="events", to="matches.analysisrun")),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="matches.match")),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="matches.matchperiod")),
                ("player", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="match_events", to="matches.player")),
                ("recipient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="received_events", to="matches.player")),
                ("recipient_track", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recipient_events", to="matches.track")),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="matches.team")),
            ],
            options={
                "ordering": ["video_time_ms"],
                "indexes": [models.Index(fields=["match", "event_type"], name="event_match_type_idx"), models.Index(fields=["match", "review_status"], name="event_match_review_idx"), models.Index(fields=["match", "player"], name="event_match_player_idx")],
            },
        ),
        migrations.CreateModel(
            name="TeamMatchStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("minutes_played", models.FloatField(default=0)),
                ("metrics", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analysis_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="team_stats", to="matches.analysisrun")),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="team_stats", to="matches.match")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="match_stats", to="matches.team")),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("match", "team"), name="unique_team_match_stat")]},
        ),
        migrations.CreateModel(
            name="PlayerMatchStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("minutes_played", models.FloatField(default=0)),
                ("metrics", models.JSONField(default=dict)),
                ("heatmap", models.JSONField(blank=True, default=list)),
                ("touchmap", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analysis_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="player_stats", to="matches.analysisrun")),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="player_stats", to="matches.match")),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="match_stats", to="matches.player")),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("match", "player"), name="unique_player_match_stat")]},
        ),
    ]
